### ISSUE TITLE
Running queries?

### ISSUE THREAD

**Issue by ShaulZuarets** [johnlpage/POCDriver#40]
Hi,
I would like to use this tool to stress test our DB, however, the way we use it is using queries and not GET operations (get by the document key).
Do you plan to support queries?

**Comment by johnlpage** [comment]
Hi,
   What you describe as a 'Get by the Document key' is actually a query on
_id which in MongoDB is a secondary index the same as a single field index
on any other field. Stress testing of your Schema, Queries and Indexes is
something for which you need to write load tests for your own
infrastructure and code rather than it being so much a test of the
hardware. POCDriver has a few other capabilities like range queries and
workflow modeling however if your plan is to verify your own query design
it's not the tool for you.
   I strongly recommend contacting MongoDB professional services for some
expert advice on testing and sizing if you feel this something you need to
do.


{ name     : "John Page",
  title    : "Distinguished Engineer",
  phone    : "(44) 755 737 1664",
  location : "Glasgow, UK" }
